### ISSUE TITLE
TokenVault crashes

### ISSUE THREAD

**Issue by fegyi001** [standardnotes/extensions#2] opened 2020-08-04 21:19 UTC
I recently installed TokenVault Extension on an iOS device (iPhone SE). Every time I try to open the camera from the app to scan a QR code, Standard Notes simply exits. Quite frustrating and making the extension quite useless.

**Comment by JaspalSuri** [comment] 2020-08-05 06:46
Hi, we're aware of [this issue](https://github.com/sn-extensions/token-vault/issues/15). I'm afraid that it's difficult to debug, but the good news is that you can ask most providers for a Secret Key, which is an alphanumeric 16-character-long key that you can paste into the "Secret" field of the TokenVault editor (when adding a new account/service). 

I'm going to close this issue since it's a duplicate of the other one, but feel free to let me know if you have any other questions!

**Closed as completed by JaspalSuri** 2020-08-05 06:46 UTC

**Comment by fegyi001** [comment] 2020-08-05 06:50
I understand that you close this issue since it is a duplicate, but in this case the other one should not be closed. But it is. Please reopen the other one, if something is difficult to debug does not mean that it should be closed.
